### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by cristeacosmin** [ColorlibHQ/illdy-companion#15]
- [x] stop using extract https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#dont-extract

- [x] improve readability in default values verification (merely an example)
```
	if ( ! isset( $instance['title'] ) ) {
		$instance['title'] = '';
	}
	if ( ! isset( $instance['image_src'] ) ) {
		$instance['image_src'] = '';
	}
	if ( ! isset( $instance['image_pos'] ) ) {
		$instance['image_pos'] = 'left';
	}
	if ( ! isset( $instance['body_content'] ) ) {
		$instance['body_content'] = '';
	}
	if ( ! isset( $instance['button1'] ) ) {
		$instance['button1'] = '';
	}
	if ( ! isset( $instance['button2'] ) ) {
		$instance['button2'] = '';
	}
	if ( ! isset( $instance['button1_link'] ) ) {
		$instance['button1_link'] = '';
	}
	if ( ! isset( $instance['button2_link'] ) ) {
		$instance['button2_link'] = '';
	}
	if ( ! isset( $instance['border_bottom'] ) ) {
		$instance['border_bottom'] = '';
	}
```

to 

```
$defaults = array(
	'title'         => __( 'Title', 'illdy' ),
	'image_src'     => '',
	'image_pos'     => 'left',
	'body_content'  => '',
	'button1'       => '',
	'button2'       => '',
	'button1_link'  => '',
	'button2_link'  => '',
	'border_bottom' => '',
);

$instance = wp_parse_args( $instance, $defaults );
```

- [x] Counter Widget add selective refresh
- [x] Person Widget add selective refresh
- [x] Project Widget add selective refresh
- [x] Recent posts Widget add selective refresh
- [x] Service Widget add selective refresh
- [x] Skill Widget add selective refresh
- [x] Testimonial Widget add selective refresh

- [x] widgets/class-widget-counter.php:47 translating ints ????
- [x] widgets/class-widget-counter.php:95 sanitize with sanitize_text_field instead of esc_html

- [x] widgets/class-widget-person.php:115 sanitization instead of escaping
- [x] widgets/class-widget-person.php:176 urls should be sanitized with esc_url_raw, not esc_url
- [x] widgets/class-widget-person.php:185 if it's a color field, you should be sanitizing with sanitize_hex_color()
- [x] esc_* functions are used for outputting information, should not be used to prepare data to be saved in DB, use sanitize_* or other means to sanitize inputs (strip tags, stripslashes, etc)
- [x] scripts that are enqueued specifically for the companion widgets should be included in the plugin, not in the theme
- [x] theme functions used in the plugin, should have at least a fallback somewhere in the plugin files. If the user changes theme, it may throw fatal error.

- [x] widgets/class-widget-project.php:36 <- sanitizing instead of escaping
- [x] widgets/class-widget-project.php:77 <- sanitizing instead of escaping
- [x] widgets/class-widget-project.php - escape echoes
- [x] widgets/class-widget-project.php:110, 111 <- sanitize with esc_url_raw

- [x] widgets/class-widget-recent-posts.php:26 don't know where to start ( escaping, logic ) - should be revised

- [x] widgets/class-widget-service.php:796 use sanitize functions instead of escape functions
- [x] widgets/class-widget-service.php:721, get_fontawesome_icons() please take a closer look ( i don't understand the foreach at the end )
- [x] get_fontawesome_icons is used in multiple widgets, it should be put in a "helper" or found some common ground so it can be maintained properly

- [x] widgets/class-widget-testimonial.php:69 sanitization instead of escaping
- [x] widgets/class-widget-testimonial.php:105 use sanitization functions 
- [x] widgets/class-widget-testimonial.php:106 sanitizing urls should be done with esc_url_raw

- [x] illdy-companion.php escape variable output
- [x] illdy-companion.php:15 don't forget to bump version here also

**Comment by cristianraiber** [comment]
This has been implemented.
