### ISSUE TITLE
HTTP ERROR 500 with  customizer

### ISSUE THREAD

**Issue by a-support** [ColorlibHQ/illdy-companion#16]
The Illdy companion plugin causes a HTTP 500 error when activated.

**Comment by cristianraiber** [comment]
@a-support - can I please get more details about this issue? what's your PHP version? could I get a screenshot of the issue? would you be willing to send login credentials to raibercristian@gmail.com so I could login and investigate this issue on my own?

**Comment by cristianraiber** [comment]
Closing since @a-support  didn't respond for 4 months. 

I tried replicating, but this issue never happened in my tests.
