### ISSUE TITLE
Fatal error: Class 'Epsilon_Editor_Custom_Control' not found in C:\xampp\htdocs\wordpress\wp-content\plugins\illdy-companion\illdy-companion.php on line 345

### ISSUE THREAD

**Issue by blackHawk007** [ColorlibHQ/illdy-companion#17]

**Comment by cristianraiber** [comment]
@blackHawk007 - I'm going to assume you've tried downloading Illdy Companion from GitHub using the internal downloader? 

If so, please follow the instructions from here: https://github.com/puikinsh/Activello#repository-clonedownload-fire-fire-fire

**Comment by cristianraiber** [comment]
Closing this as we haven't received an answer from the OP.
