### ISSUE TITLE
Demo import doesn't work

### ISSUE THREAD

**Issue by nodarik** [ColorlibHQ/illdy-companion#27]
Simply try to import demo on the fresh installation of the WordPress, it's not working

**Comment by mahendrapratap4022** [comment]
Hi @nodarik it is fixed in https://github.com/ColorlibHQ/illdy-companion/pull/28

**Comment by nodarik** [comment]
@mahendrapratap4022 Thank you man for superfast reaction ;-)

**Comment by mahendrapratap4022** [comment]
My pleasure @nodarik 😊

**Comment by ad-pixdev** [comment]
Same issue with latest Illdy theme (v2.1.9)

Found workaround :

in file `/inc/libraries/welcome-screen/class-epsilon-welcome-screen.php`, line **219**, add `'Illdy_Companion_Import_Data'` to array list like this :

```php
if ( ! in_array( $args_action[0], array( 'Epsilon_Import_Data', 'Epsilon_Welcome_Screen', 'Illdy_Companion_Import_Data' ) ) || ! class_exists( $args_action[0] ) ) {
```

works fine for me.

**Comment by MaxBayne** [comment]
> Same issue with latest Illdy theme (v2.1.9)
> 
> Found workaround :
> 
> in file `/inc/libraries/welcome-screen/class-epsilon-welcome-screen.php`, line **219**, add `'Illdy_Companion_Import_Data'` to array list like this :
> 
> ```
> if ( ! in_array( $args_action[0], array( 'Epsilon_Import_Data', 'Epsilon_Welcome_Screen', 'Illdy_Companion_Import_Data' ) ) || ! class_exists( $args_action[0] ) ) {
> ```
> 
> works fine for me.

thanks so much , its working for me :)
